[package]
name = "dummy_issuer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# IC Dependencies
candid.workspace = true
ic-cdk.workspace = true
ic-cdk-macros.workspace = true
ic-certification = "2.2"
# II Dependencies
vc_util = { git="https://github.com/dfinity/internet-identity", rev="1417991b69660046cc0b4f1ea93a5903b037f3b1" }
canister_sig_util = { git="https://github.com/dfinity/internet-identity", rev="1417991b69660046cc0b4f1ea93a5903b037f3b1" }
identity_jose = { git = "https://github.com/frederikrothenberger/identity.rs.git", branch = "frederik/wasm-test", default-features = false, features = ["iccs"]}
identity_credential = { git = "https://github.com/frederikrothenberger/identity.rs.git", branch = "frederik/wasm-test", default-features = false , features = ["validator"] }
identity_core = { git = "https://github.com/frederikrothenberger/identity.rs.git", branch = "frederik/wasm-test", default-features = false }
# Other dependencies
serde_bytes = "0.11"
serde_json = "1"
lazy_static = "1.4"
sha2 = "^0.10" # set bound to match ic-certified-map bound

[dev-dependencies]
pocket-ic = "3.1.0"
serde = { version = "1", features = ["derive"] }
