[package]
name = "dummy_issuer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid.workspace = true
ic-cdk.workspace = true
ic-cdk-macros.workspace = true
vc_util = { git="https://github.com/dfinity/internet-identity", rev="1417991b69660046cc0b4f1ea93a5903b037f3b1" }
serde_bytes = "0.11"
